### ISSUE TITLE
Please add `ddev-get` label, add link to README

### ISSUE THREAD

**Issue by rfay** [Metadrop/ddev-aljibe#1] opened 2024-07-16 12:34 UTC
This will be discoverable via `ddev get --list --all` if you add the `ddev-get` label.

Could you also please add a link to aljibe in the README? There might be somebody like me who hasn't heard of it.

**Comment by rsanzante** [comment] 2024-07-16 13:44
Thank for the issue report!

We have added the `ddev-get` topic. Also, we have tried to clarify what Aljibe is: an extension to DDEV to develop Drupal sites with some development tools ready to be used like different kinds of testing (BDD, visual regression testing, Lighthouse checks, accesibility...)

Aljibe is now being displayed when running `ddev get --list --all`.

It is still in alpha stage, though.

I'm closing this because I think it is done. Feel free to reopen or add any question you may have.

**Closed by rsanzante** 2024-07-16 13:44 UTC

**Comment by rfay** [comment] 2024-07-16 13:53
You might want to add to the README references to (and differences between) this and 
* https://github.com/ddev/ddev-selenium-standalone-chrome
* https://github.com/tyler36/ddev-cypress

**Comment by juanjol** [comment] 2024-09-01 20:47
Hi @rfay, sorry for the delay in responding to this. We still have a lot of work to do on the README to document how Aljibe works.

As @rsazante comments Aljibe is the name we have given to this add-on, which is actually our way of generating a complete Drupal environment based on ddev. It's not a tool that existed before.
That said, Aljibe is a compendium of plugins that provide testing tools at different levels, adapted to some extent to a folder structure that we think is useful, so maybe the comparison you propose should not go in this README (at least at first) but in the adaptations and forks that we have made for the different tools that aljibe installs.

What we will do is to list those tools and reference them to their repositories where that comparison will be. We will also add the tag to those repositories so that they appear in the list as you proposed.

Thank you very much for your comments and your work @rfay.
